print("Buenas tardes")
print("hoy es 10 de abril del 2025")
input()
print("hoy estamos estudiando en el cetpro puno")
input()
print('Estamos en Puno')
input()
print('¿Cómo te llamas?')
n=input()
print('Hola',n,'encantado de conocerte')
